name: handoff
description: "A Flutter plugin for Apple's Handoff functionality."
version: 0.1.0
homepage: https://github.com/mastermakrela/flutter-handoff

environment:
  sdk: ^3.8.1
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: HandoffPlugin
